from abc import ABC, abstractmethod
from typing import AsyncIterator, List, Dict, Any

class AIProvider(ABC):
    @abstractmethod
    async def generate_stream(
        self,
        messages: List[Dict[str, str]],
        system_prompt: str,
        temperature: float,
        max_tokens: int,
    ) -> AsyncIterator[str]:
        """
        Yields text chunks as they are generated by the model.
        """
        pass

    @abstractmethod
    async def generate_embeddings(self, text: str) -> List[float]:
        """
        Generates a vector embedding for the input text.
        """
        pass

    @abstractmethod
    async def list_models(self) -> List[str]:
        """
        Returns a list of available model names.
        """
        pass
